<?php
/**
 * description
 *
 *
 * @category    category
 * @package     package
 * @author      Sonia Fajardo <sonialfajardo88@gmail.com>
 * @version     $Id:  $
 */

$tabIndex = 3;

echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>Sonia Fajardo</title>
        <meta name="keywords" content="Sonia Fajardo, Sonia L Fajardo, Sonia Liliana Fajardo, Python, JavaScript, AngularJS, Software Engineer, Java, Front end developer, Full stack engineer, Web Developer, Colombia, Bogota, San Francisco, SF, ReactJS"/>
        <meta name="description" content="Information about Sonia Fajardo."/>
        <meta name="author" content="Sonia Fajardo"/>
        <meta name="revised" content="Sonia Fajardo, <?php echo date('d-m-Y');?>"/>
        <meta http-equiv="Content-Language" content="en"/>
        <meta name="language" content="en"/>
		<link rel="stylesheet" type="text/css" href="http://soniafajardo.com/style.css"/>

        <script type="text/javascript"><!--
        var tabIndex=0;
        function email(user, host) {
            e = user + '@';
            for (i = 0; i < host.length - 1; i++) { e = e + host[i] + '.'; }
            e = e + host[host.length - 1] ;
            document.writeln('<a href="mailto:' + e + '" title="' + e + '" tabindex="' + tabIndex++ + '">' + e + '</a>');
        }//-->
        </script>
    </head>
    <body>
	<div id="wrapper">
        <div id="title">
            <h1>Sonia Fajardo</h1>
            <div class="contact">
                <h5>
                    <script type="text/javascript">email('sonialfajardo88', [ 'gmail', 'com' ]);</script>
                    <noscript><address>sonialfajardo88 at gmail dot com</address></noscript>
                </h5>
                <h5>
                    <script type="text/javascript">email('sonia', [ 'brightroll', 'com' ]);</script>
                    <noscript><address>sonia at brightroll dot com</address></noscript>
                </h5>
            </div>
        </div>
        <div>
            <div>
                <h3>About me</h3>
				<p>
                    I am a Software Engineer currently working at <a href="http://www.brightroll.com/" title="BrightRoll" target="_blank">BrightRoll</a>. I've been there for over a year, and was initially doing back-end development in order to build APIs and other services critical to BrightRoll's video ad-serving infrastructure. More recently, I've been focusing on front-end development in order to build the brand new demand-side platform that BrightRoll offers.
                </p>
                <p>
                    Before BrightRoll, I worked at <a href="http://www.radius.com/" title="Radius" target="_blank">Radius</a> for about 3 years. I worked on developing its predictive marketing software, and was able to work on different aspects of the development process, including back-end and front-end web development.
                </p>
                <p>
                    Previously, I was working at <a href="http://www.cisco.com/" title="Cisco" target="_blank">Cisco Systems</a>
                    in the Digital Media Systems Business Unit developing web applications for the Digital Signage product.
                </p>
                <p>
                    While attending Georgia Tech, I enrolled in the explorer summer internship program at Microsoft in my 2nd year.
                    During my 3rd year, I joined Google for a summer internship in Santa Monica, CA.
                </p>
				<p>				
					I am originally from Bogot&aacute;, Colombia and came to the U.S. to continue my Industrial Engineering studies. However, after taking a few programming classes, I decided to enroll in the Computer Science program
					at <a href="http://www.gatech.edu/" title="Georgia Tech" target="_blank">Georgia Tech</a>. I graduated in the summer of 2008 with highest honors.
                </p>
                <p>
                    I love riding my bike in and around San Francisco, and I'm always searching for new places to see when going on rides around the bay!
                </p>
                <hr />
				<h3>Coding stuff</h3>
				<p>
                    This is a <a href="http://soniafajardo.com/plugins/emailPlugin.htm" title="Plugin">jQuery email Plugin</a> I created which helps protect your email from spam when you post it on your website.
                </p>
				<p>
                    This is my <a href="http://soniafajardo.blogspot.com/" title="Blog">Blog</a> on Flex/ActionScript where I keep some useful tips I have used. 
                </p>
            </div>
            <hr />
			<div>
                <h3>Social media</h3>
				<p>
					<a href="https://twitter.com/sonialfajardo" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @sonialfajardo</a>
                    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
				</p>
				<p>
					<a href="http://www.linkedin.com/in/sonialfajardo"><img src="http://www.linkedin.com/img/webpromo/btn_myprofile_160x33.png" width="160" height="33" style="border:0px" alt="View Sonia Fajardo's profile on LinkedIn" /></a>
				</p>
                <p>
                    <a href="http://about.me/soniafajardo" target="_blank">about.me</a> profile
                </p>
			</div>
		</div>
        <hr />
        <div>
            <h3>Check out my blog posts on Medium</h3>
            <script async src="https://static.medium.com/embed.js"></script><a class="m-profile" href="https://medium.com/@sonialfajardo">Sonia Fajardo</a>
        </div>
	</div>
	
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-5047079-2']);
	  _gaq.push(['_trackPageview']);

	  (function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
</html>